### ISSUE TITLE
AMQP 1.0 or 0.9.1

### ISSUE THREAD

**Issue by leonardlin** [puzzle-org/amqp#43]
Hi, sorry for abusing the issue system, but I couldn't find any other ways to get in touch.

This looks like an awesome library. Is it for AMQP 1.0 or 0.9.1?

The doc says 1.0 but all examples are with rabbitmq.

I'm looking for a 1.0 library.

Thanks for your help.

**Comment by Niktux** [comment]
Sorry for very (too) late reply, I didn't receive notification for your issue.
We using our library everyday in production but exclusively with rabbitmq and AMQP 0.9.1
Never tester with AMQP 1.0
